from agent_smith_ai.utility_agent import UtilityAgent

import textwrap
import os
from typing import Any, Dict



## A UtilityAgent can call API endpoints and local methods
class EvoKgAgent(UtilityAgent):

    def __init__(self, name, model = "gpt-4o-mini", openai_api_key = None, auto_summarize_buffer_tokens = 500):
        
        ## define a system message
        system_message = textwrap.dedent(f"""
You are the Evo-KG Assistant, an AI-powered chatbot designed to answer questions about data from the Evo-KG knowledge graph. 
Evo-KG contains information on the following entity types: Gene, Protein, Disease, Chemical, Phenotype, Aging_Phenotype, Epigenetic_Modification, Tissue, AA_Intervention, Hallmark, Metabolite.

Relations in the Knowledge Graph:
The knowledge graph supports the following relations between entities:

AA_INTERVENTION_HALLMARK
DISEASE_DISEASE
DISEASE_DRUG
DISEASE_GENE
DISEASE_PHENOTYPE
DISEASE_PROTEIN
DRUG_AGING_PHENOTYPE
DRUG_DISEASE
DRUG_DRUG
DRUG_GENE
DRUG_PROTEIN
GENE_AGING_PHENOTYPE
GENE_DISEASE
GENE_DRUG
GENE_EPIGENETIC_MODIFICATION
GENE_GENE
GENE_HALLMARK
GENE_METABOLITE
GENE_PHENOTYPE
GENE_PROTEIN
GENE_TISSUE
METABOLITE_METABOLITE
PHENOTYPE_PHENOTYPE
PROTEIN_DISEASE
PROTEIN_DRUG
PROTEIN_GENE
PROTEIN_PROTEIN

Note:
For the entity type Chemical, all relations are prefixed with DRUG_ and/or suffixed with _DRUG, rather than using CHEMICAL_.

Entity Identifiers:
Each entity is uniquely identified by its respective id or name:

Gene id
Protein id
Disease name
Chemical id
Phenotype name
Aging_Phenotype name 
Epigenetic_Modification name
Tissue name
AA_Intervention name
Hallmark name
Metabolite name

Guidelines:
If Evo-KG does not contain the requested information, supplement with data generated by the OpenAI GPT-4 model.
When GPT-4-generated information is used, explicitly mention that the content is not from Evo-KG and is provided by GPT-4.
You STRICLTY NEED TO ONLY answer questions directly related to the Evo-KG knowledge graph or supplement as described above.""").strip()
        
        super().__init__(name,                                             # Name of the agent
                         system_message,                                   # Openai system message
                         model = model,                     # Openai model name
                         openai_api_key = openai_api_key,    # API key; will default to OPENAI_API_KEY env variable
                         auto_summarize_buffer_tokens = auto_summarize_buffer_tokens,               # Summarize and clear the history when fewer than this many tokens remains in the context window. Checked prior to each message sent to the model.
                         summarize_quietly = False,                        # If True, do not alert the user when a summarization occurs
                         max_tokens = None,                                # maximum number of tokens this agent can bank (default: None, no limit)
                         token_refill_rate = 50000.0 / 3600.0)             # number of tokens to add to the bank per second

        ## register some API endpoints (inherited from UtilityAgent)
        ## the openapi.json spec must be available at the spec_url:
        ##    callable endpoints must have a "description" and "operationId"
        ##    params can be in body or query, but must be fully specified
        self.register_api("monarch", 
                          spec_url = "https://neo4j-fastapi.vercel.app/openapi.json", 
                          base_url = "https://neo4j-fastapi.vercel.app",
                          callable_endpoints = [
                                                'get_entity',
                                                'get_subgraph',
                                                'predict_tail',
                                                'get_prediction_rank',
                                                'check_relationship',
                                                'get_entity_relationships',
                                                ])